<!DOCTYPE html>
<html>
<head>
    <title>
        BeProud.Love
    </title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Nerko+One&display=swap" rel="stylesheet">
    <style>
        .rainbow-text{
            background-image: linear-gradient(to left, violet, indigo, blue, green, yellow, orange, red);
            -webkit-background-clip: text;
            -moz-background-clip: text;
            background-clip: text;
            color: transparent;
            font-family: 'Nerko One', cursive;
            text-align: center;
        }
    </style>
</head>
<body>  
    <h1 class="rainbow-text">
        BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD BE PROUD 
    </h1>
    
</body>
</html>